kumuluzee:
  name: image-managing
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://image-managing:8080
    http:
      port: 8080
  config:
    etcd:
      hosts: http://etcd:2379

configuration-properties:
  users-parameter: file
