kumuluzee:
  name: image-managing
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  config:
    etcd:
      hosts: http://etcd:2379
  health:
    checks:
      etcd-health-check:
        connection-url: http://etcd:2379/health

configuration-properties:
  demo-etcd-parameter: file
  demo-service-is-healthy: true
